CREATE TABLE raw_materials (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR2(255) NOT NULL,
                               stock_quantity NUMBER(19, 2) DEFAULT 0 NOT NULL
);

CREATE TABLE products (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR2(255) NOT NULL,
                          price NUMBER(19, 2) NOT NULL
);

CREATE TABLE product_materials (
                                   product_id NUMBER NOT NULL,
                                   material_id NUMBER NOT NULL,
                                   required_quantity NUMBER(19, 2) NOT NULL,
                                   CONSTRAINT pk_product_materials PRIMARY KEY (product_id, material_id),
                                   CONSTRAINT fk_pm_product FOREIGN KEY (product_id) REFERENCES products(id),
                                   CONSTRAINT fk_pm_material FOREIGN KEY (material_id) REFERENCES raw_materials(id)
);