INSERT INTO raw_materials (name, stock_quantity) VALUES ('Steel Plate', 500.0);
INSERT INTO raw_materials (name, stock_quantity) VALUES ('Electronic Component', 1000.0);
INSERT INTO raw_materials (name, stock_quantity) VALUES ('Industrial Plastic', 800.0);
INSERT INTO raw_materials (name, stock_quantity) VALUES ('Copper Wiring', 1200.0);
INSERT INTO raw_materials (name, stock_quantity) VALUES ('Aluminum Casting', 300.0);
INSERT INTO raw_materials (name, stock_quantity) VALUES ('Lithium Battery', 50.0);
INSERT INTO raw_materials (name, stock_quantity) VALUES ('Fiber Optic Cable', 200.0);

INSERT INTO products (name, price) VALUES ('Industrial Robot Arm', 15000.00);
INSERT INTO products (name, price) VALUES ('Control Panel', 2500.00);
INSERT INTO products (name, price) VALUES ('Sensor Case', 150.00);
INSERT INTO products (name, price) VALUES ('Automated AGV', 45000.00); -- Produto mais caro
INSERT INTO products (name, price) VALUES ('Smart Gateway', 1200.00);
INSERT INTO products (name, price) VALUES ('Heavy Duty Motor', 8500.00);

INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (1, 1, 10.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (1, 2, 20.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (1, 4, 15.0);

INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (2, 1, 2.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (2, 2, 5.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (2, 3, 5.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (2, 4, 10.0);

INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (3, 2, 1.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (3, 3, 2.0);

INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (4, 1, 50.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (4, 5, 20.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (4, 6, 2.0);

INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (5, 2, 8.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (5, 4, 5.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (5, 7, 10.0);

INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (6, 1, 25.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (6, 4, 40.0);
INSERT INTO product_materials (product_id, material_id, required_quantity) VALUES (6, 5, 10.0);

ALTER TABLE products MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE raw_materials MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE);

COMMIT;